[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
line-length = 95
target-version = ["py37", "py38", "py39"]

[tool.isort]
profile = "black"
line_length = 95
src_paths = ["taxi"]
