[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 95
target-version = ["py37", "py38", "py39"]

[tool.isort]
profile = "black"
line_length = 95
src_paths = ["taxi"]
